name:                th-crash-repro

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns
- MultiWayIf
- TupleSections
- NumericUnderscores
- TypeApplications

ghc-options:
- -Wunused-packages
- -Wall
- -fno-warn-name-shadowing

library:
  source-dirs: src

executables:
  th-crash-repro:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - aeson
    - th-orphans
