name:                th-crash-repro
version:             0.5.1.0

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- lsp-types >= 2.0.0.1
- monad-logger
- string-interpolate
- text
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns
- MultiWayIf
- TupleSections
- NumericUnderscores
- TypeApplications

ghc-options:
- -Wunused-packages
- -Wall
- -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
  - base
  - th-orphans

executables:
  th-crash-repro:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - aeson
